    [[redirects]]
      from = "/api/model/*"
      to = "https://teachablemachine.withgoogle.com/models/iXNypx5mp/:splat"
      status = 200

    [[redirects]]
      from = "/api/metadata/*"
      to = "https://teachablemachine.withgoogle.com/models/iXNypx5mp/:splat"
      status = 200